### ISSUE TITLE
RadListView: app crashes on Android

### ISSUE THREAD

**Issue by alexrainman** [telerik/nativescript-ui-samples#27]
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.nativescript.HelloWorld/
com.tns.NativeScriptActivity}: com.tns.NativeScriptException: NativeScript application not initialized correctly. getActivity method returned invalid value.

Error: Cannot create module /data/data/org.nativescript.HelloWorld/files/app/tns_modules/
nativescript-telerik-ui/listview. TypeError: Cannot read  property 'extend' of undefined. StackTrace:
TypeError: Cannot read property 'extend' of undefined at __extends (/data/data/org.nativescript.HelloWorld/files/internal/prepareExtend.js:54:12)
at /data/data/org.nativescript.HelloWorld/files/app/tns_modules/nativescript-telerik-ui/listview.js:22:5 at ...
```

**Comment by ginev** [comment]
Hello @alexrainman,
This seems like an issue related to missing native types. I suppose you haven't added the RecyclerView appcompat library as a dependency of your application. Please take a look at Getting started documentation article here:

http://docs.telerik.com/devtools/nativescript-ui/Controls/ListView/listview-getting-started

Basically, RadListView, when run on Android, depends on the standard RecyclerView component which is implemented in the RecyclerView appcompat library. As of now, this library is added manually to your NativeScript application by modifying the build.gradle file of the Android platform as described in the help.

I hope this helps.

**Comment by alexrainman** [comment]
I did the change to my build file, i may be missing something in my Android SDK folder, don't you think?

**Comment by alexrainman** [comment]
I made it work changing it to this:

```
dependencies {
	def suppotVer = "23.1.0";
	if(project.hasProperty("supportVersion")) {
		suppotVer = supportVersion
	}
	
    compile "com.android.support:support-v4:$suppotVer"
    compile "com.android.support:appcompat-v7:$suppotVer"
    compile "com.android.support:recyclerview-v7:23.1.0"
```

Anyway, now it crashes when i do a pull to refresh and i try to clean the array to populate it again and, action buttons are not visible in android when i swipe, only a white space is shown. Are you planning to sell this UI package by itself?

**Comment by alexrainman** [comment]
It was crashing because i was trying to clear the array before adding the refreshed items.

_items.splice(0, _items.length) doesn't works. 

This works:

```
for (var i = 0; i < that.get()._items.length; i++) {
       that.get()._items.pop();
}
```

Cell buttons still not visible in Android. I created another thread for it.

**Comment by ginev** [comment]
Hello @alexrainman ,

Thanks for writing back.

1. The issue with using `_items.splice` has been resolved in our internal codebase and we will be published an update very soon.

2. Regarding the `build.gradle` modifications: can you open your Android SDK Manager and see if there aren't any pending updates available for the support libraries? If it doesn't work using the `$suppotVer` placeholder for the `recyclerview` library, it shouldn't be working for the `appcompat` library as well.

3. I cannot exactly say why your Swipe actions are not visible. Did you define a `itemSwipeTemplate` as described here: [http://docs.telerik.com/devtools/nativescript-ui/Controls/ListView/listview-features-swipe-to-execute](http://docs.telerik.com/devtools/nativescript-ui/Controls/ListView/listview-features-swipe-to-execute)

4. Telerik UI for NativeScript is currently in Preview version. Once we polish its API and address the bugs we have identified, we plan to release it officially and sell it.

Let me know if additional help is needed.

**Comment by alexrainman** [comment]
Swipe actions are not visible in Android even running you sdk sample code but i guess it's a preview version ;)

**Comment by alexrainman** [comment]
I updated to {N} 1.4.x CLI and now the Android issue is back. It seems reciclerview cannot be found :(

**Comment by alexrainman** [comment]
I am back to this:
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.nativescript.HelloWorld/
com.tns.NativeScriptActivity}: com.tns.NativeScriptException: NativeScript application not initialized correctly. getActivity method returned invalid value.

Error: Cannot create module /data/data/org.nativescript.HelloWorld/files/app/tns_modules/
nativescript-telerik-ui/listview. TypeError: Cannot read  property 'extend' of undefined. StackTrace:
TypeError: Cannot read property 'extend' of undefined at __extends (/data/data/org.nativescript.HelloWorld/files/internal/prepareExtend.js:54:12)
at /data/data/org.nativescript.HelloWorld/files/app/tns_modules/nativescript-telerik-ui/listview.js:22:5 at ...
```

**Comment by alexrainman** [comment]
Now TabView works inside SideDrawer.mainContent  in iOS

**Comment by alexrainman** [comment]
All my issues are solved and i had to make multiple fixes to achieve it.

1. I updated ```tns``` CLI to the latest version.
2. I had to copy support library installed files from ```extras/android/m2repository/com``` folder to ```android/google/m2repository/com``` folder. I notice in console that ```tns``` was looking for the files in the second one but the files weren't there.
3. I had to edit the ```build.gradle``` file and set ```compileSdk = 24```, ```targetSdk  = 24```, ```buildToolsVersion = 24.4.1```, ```suppotVer = "23.1.0"``` plus adding ```compile "com.android.support:recyclerview-v7:$suppotVer"```

Now only one small issue. With this code:

```
<drawer:RadSideDrawer.mainContent>
        <TabView>
            <TabView.items>
                <TabViewItem title="Tab 1">
                    <TabViewItem.view>
                        <lv:RadListView items="{{ dataItems }}" row="1"
                                        pullToRefresh="true"
                                        shouldRefreshOnPull="{{ onShouldRefreshOnPull }}"
                                        loadOnDemandMode="Auto"
                                        shouldLoadMoreData="{{ onLoadMoreItemsRequested }}"
                                        selectionBehavior="None"
                                        itemTap="{{ onItemClick }}"
                                        swipeCells="true"
                                        startSwipeCell="{{ onSwipeCellStarted }}"
                                        didFinishSwipeCell="{{ onSwipeCellFinished }}">
                            <lv:RadListView.listViewLayout>
                                <lv:ListViewLinearLayout itemHeight="50" scrollDirection="Vertical"/>
                            </lv:RadListView.listViewLayout>
                            <lv:RadListView.itemTemplate>
                                <StackLayout orientation="vertical">
                                    <Label fontSize="20" text="{{ itemName }}" cssClass="cellTitle" />
                                    <Label fontSize="14" text="{{ itemDescription }}" cssClass="cellDetail" />
                                </StackLayout>
                            </lv:RadListView.itemTemplate>
                            <lv:RadListView.itemSwipeTemplate>
                                <GridLayout columns="auto, *, auto">
                                    <Button col="0" cssClass="cellLeftBtn" text="Fold"/>
                                    <Button col="2" cssClass="cellRightBtn" text="Delete"/>
                                </GridLayout>
                            </lv:RadListView.itemSwipeTemplate>
                        </lv:RadListView>
                    </TabViewItem.view>
                </TabViewItem>
                <TabViewItem title="Tab 2">
                    <TabViewItem.view>
                        <Label text="Label in Tab2" />
                    </TabViewItem.view>
                </TabViewItem>
            </TabView.items>
        </TabView>
    </drawer:RadSideDrawer.mainContent>
```

The RadListView is visible in iOS but not in Android, but, if i wrap the ListView into ```StackLayout``` then it's the opposite thing.

Cheers!

**Comment by ginev** [comment]
Hey @alexrainman,
good to hear that you've managed to resolve your issues. I've actually reported your feedback to the CLI team so that they take a look at the Android SDK issues as well.

I have also posted an answer to the thread where you have shared your project regarding the Swipe templates - so let me know if you have any questions in that aspect: #26.
